const teamAbbMap = {
    "Baltimore Orioles": "bal",
    "Boston Red Sox": "bos",
    "New York Yankees": "nyy",
    "Tampa Bay Rays": "tb",
    "Toronto Blue Jays": "tor",
    "Chicago White Sox": "cws",
    "Cleveland Guardians": "cle",
    "Detroit Tigers": "det",
    "Kansas City Royals": "kc",
    "Minnesota Twins": "min",
    "Houston Astros": "hou",
    "Los Angeles Angels": "laa",
    "Athletics": "oak",
    "Seattle Mariners": "sea",
    "Texas Rangers": "tex",
    "Atlanta Braves": "atl",
    "Miami Marlins": "mia",
    "New York Mets": "nym",
    "Philadelphia Phillies": "phi",
    "Washington Nationals": "was",
    "Chicago Cubs": "chc",
    "Cincinnati Reds": "cin",
    "Milwaukee Brewers": "mil",
    "Pittsburgh Pirates": "pit",
    "St. Louis Cardinals": "stl",
    "Arizona Diamondbacks": "ari",
    "Colorado Rockies": "col",
    "Los Angeles Dodgers": "lad",
    "San Diego Padres": "sd",
    "San Francisco Giants": "sf"
}

module.exports = { teamAbbMap };