const teamAbbMap = {
    "Baltimore Orioles": "bal",
    "Boston Red Sox": "bos",
    "New York Yankees": "nyy",
    "Tampa Bay Rays": "tb",
    "Toronto Blue Jays": "tor",
    "Chicago White Sox": "cws",
    "Cleveland Guardians": "cle",
    "Detroit Tigers": "det",
    "Kansas City Royals": "kc",
    "Minnesota Twins": "min",
    "Houston Astros": "hou",
    "Los Angeles Angels": "laa",
    "Athletics": "oak",
    "Seattle Mariners": "sea",
    "Texas Rangers": "tex",
    "Atlanta Braves": "atl",
    "Miami Marlins": "mia",
    "New York Mets": "nym",
    "Philadelphia Phillies": "phi",
    "Washington Nationals": "was",
    "Chicago Cubs": "chc",
    "Cincinnati Reds": "cin",
    "Milwaukee Brewers": "mil",
    "Pittsburgh Pirates": "pit",
    "St. Louis Cardinals": "stl",
    "Arizona Diamondbacks": "ari",
    "Colorado Rockies": "col",
    "Los Angeles Dodgers": "lad",
    "San Diego Padres": "sd",
    "San Francisco Giants": "sf"
}

const teamIdMap = {
    108: "Los Angeles Angels",
    109: "Arizona Diamondbacks",
    110: "Baltimore Orioles",
    111: "Boston Red Sox",
    112: "Chicago Cubs",
    113: "Cincinnati Reds",
    114: "Cleveland Guardians",
    115: "Colorado Rockies",
    116: "Detroit Tigers",
    117: "Houston Astros",
    118: "Kansas City Royals",
    119: "Los Angeles Dodgers",
    120: "Washington Nationals",
    121: "New York Mets",
    133: "Oakland Athletics",
    134: "Pittsburgh Pirates",
    135: "San Diego Padres",
    136: "Seattle Mariners",
    137: "San Francisco Giants",
    138: "St. Louis Cardinals",
    139: "Tampa Bay Rays",
    140: "Texas Rangers",
    141: "Toronto Blue Jays",
    142: "Minnesota Twins",
    143: "Philadelphia Phillies",
    144: "Atlanta Braves",
    145: "Chicago White Sox",
    146: "Miami Marlins",
    147: "New York Yankees",
    158: "Milwaukee Brewers"
}

module.exports = { teamAbbMap, teamIdMap };